name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: "Run Supervisor Tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Run Tests
        run: make -C ai.lemonade_server.Lemonade test

  flatpak-build:
    name: "Verify Flatpak Build"
    permissions:
      contents: read
    uses: ./.github/workflows/build-flatpak.yml
    with:
      branch: beta
      dry-run: true
