name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      branch:
        description: "Flatpak branch to use for build."
        required: false
        type: string
        default: "beta"
      app-id:
        description: "Verify only this app id."
        required: false
        type: string
        default: ""
      rebuild:
        description: "Force all apps to be rebuilt."
        required: false
        type: boolean
        default: false

jobs:
  test:
    name: "Run Supervisor Tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
        with:
          submodules: true

      - name: Run Tests
        run: make -C ai.lemonade_server.Lemonade test

  flatpak-build:
    name: "Verify Flatpak Build"
    permissions:
      contents: read
    uses: ./.github/workflows/build-flatpak.yml
    with:
      branch: ${{ inputs.branch || 'beta' }}
      app-id: ${{ inputs.app-id || '' }}
      force-all: ${{ inputs.rebuild || false }}
      dry-run: true
